let CardIemsObj = [
    {
        id: "1",
        productName: "Grande",
        productType: "Blossom Pouch",
        price: "$39.49",
        image: "https://images2.imgbox.com/38/dc/zwOWUdvF_o.png",
    },
    {
        id: "2",
        productName: "Coach",
        productType: "Leather Coach Bag",
        price: "$54.69",
        image: "https://images2.imgbox.com/de/04/cUdIOyc4_o.png",
    },
    {
        id: "3",
        productName: "Remus",
        productType: "Brown Strap Bag",
        price: "$57.00",
        image: "https://images2.imgbox.com/f8/d0/W1KOpcQ1_o.png",
    },
    {
        id: "4",
        productName: "Boujee",
        productType: "Black Bag",
        price: "$56.49",
        image: "https://images2.imgbox.com/9b/2f/gl7x6OYs_o.png",
    },
    {
        id: "5",
        productName: "Grande",
        productType: "Blossom Pouch",
        price: "$39.49",
        image: "https://images2.imgbox.com/38/dc/zwOWUdvF_o.png",
    },
    {
        id: "6",
        productName: "Coach",
        productType: "Leather Coach Bag",
        price: "$54.69",
        image: "https://images2.imgbox.com/de/04/cUdIOyc4_o.png",
    },
    {
        id: "7",
        productName: "Remus",
        productType: "Brown Strap Bag",
        price: "$57.00",
        image: "https://images2.imgbox.com/f8/d0/W1KOpcQ1_o.png",
    },
    {
        id: "8",
        productName: "Boujee",
        productType: "Black Bag",
        price: "$56.49",
        image: "https://images2.imgbox.com/9b/2f/gl7x6OYs_o.png",
    },
    {
        id: "9",
        productName: "Grande",
        productType: "Blossom Pouch",
        price: "$39.49",
        image: "https://images2.imgbox.com/38/dc/zwOWUdvF_o.png",
    },
    {
        id: "10",
        productName: "Grande",
        productType: "Blossom Pouch",
        price: "$39.49",
        image: "https://images2.imgbox.com/38/dc/zwOWUdvF_o.png",
    },
    {
        id: "11",
        productName: "Coach",
        productType: "Leather Coach Bag",
        price: "$54.69",
        image: "https://images2.imgbox.com/de/04/cUdIOyc4_o.png",
    },
    {
        id: "12",
        productName: "Remus",
        productType: "Brown Strap Bag",
        price: "$57.00",
        image: "https://images2.imgbox.com/f8/d0/W1KOpcQ1_o.png",
    },
    {
        id: "13",
        productName: "Boujee",
        productType: "Black Bag",
        price: "$56.49",
        image: "https://images2.imgbox.com/9b/2f/gl7x6OYs_o.png",
    },
    {
        id: "14",
        productName: "Grande",
        productType: "Blossom Pouch",
        price: "$39.49",
        image: "https://images2.imgbox.com/38/dc/zwOWUdvF_o.png",
    },
    {
        id: "15",
        productName: "Coach",
        productType: "Leather Coach Bag",
        price: "$54.69",
        image: "https://images2.imgbox.com/de/04/cUdIOyc4_o.png",
    },
    {
        id: "16",
        productName: "Remus",
        productType: "Brown Strap Bag",
        price: "$57.00",
        image: "https://images2.imgbox.com/f8/d0/W1KOpcQ1_o.png",
    },
    {
        id: "17",
        productName: "Boujee",
        productType: "Black Bag",
        price: "$56.49",
        image: "https://images2.imgbox.com/9b/2f/gl7x6OYs_o.png",
    },
    {
        id: "18",
        productName: "Grande",
        productType: "Blossom Pouch",
        price: "$39.49",
        image: "https://images2.imgbox.com/38/dc/zwOWUdvF_o.png",
    },
    {
        id: "19",
        productName: "extra",
        productType: "Blossom Pouch",
        price: "$39.49",
        image: "https://images2.imgbox.com/38/dc/zwOWUdvF_o.png",
    },
    
  ];

  export default CardIemsObj 